// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
  name = "countResult",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "countResult",
  namespace = ""
)
public class CountResult implements java.io.Serializable {

  private long _count;

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "count",
    namespace = ""
  )
  public long getCount() {
    return this._count;
  }

  /**
   * (no documentation provided)
   */
  public void setCount(long _count) {
    this._count = _count;
  }

}
