// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "accountProvisioningStatus",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlEnum (
    java.lang.String.class
)
public enum AccountProvisioningStatus {

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "WAITING_TO_START" )
    WAITING_TO_START("WAITING_TO_START"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "IN_PROGRESS" )
    IN_PROGRESS("IN_PROGRESS"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "COMPLETED" )
    COMPLETED("COMPLETED");

    private final String value;

    private AccountProvisioningStatus(String value) {
        this.value = value;
    }

    public String toString() {
        return value;
    }

}
