// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "accountServicePlan",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "servicePlan",
    namespace = "http://eurotech.com/edc/2.0"
)
public class AccountServicePlan implements java.io.Serializable {

    private java.util.Date _expirationDate;
    private int _maxNumberOfDevices;
    private int _maxNumberOfRules;
    private long _createdBy;
    private com.eurotech.cloud.apis.v2.model.AccountProvisioningStatus _provisioningStatus;
    private long _modifiedBy;
    private boolean _atDeviceLimit;
    private java.util.Date _createdOn;
    private java.util.Date _modifiedOn;
    private long _txByteLimit;
    private boolean _dataStorageEnabled;
    private long _accountId;
    private int _dataTimeToLive;
    private long _rxByteLimit;
    private com.eurotech.cloud.apis.v2.model.AccountStatus _status;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "expirationDate",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getExpirationDate() {
        return this._expirationDate;
    }

    /**
     * (no documentation provided)
     */
    public void setExpirationDate(java.util.Date _expirationDate) {
        this._expirationDate = _expirationDate;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "maxNumberOfDevices",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public int getMaxNumberOfDevices() {
        return this._maxNumberOfDevices;
    }

    /**
     * (no documentation provided)
     */
    public void setMaxNumberOfDevices(int _maxNumberOfDevices) {
        this._maxNumberOfDevices = _maxNumberOfDevices;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "maxNumberOfRules",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public int getMaxNumberOfRules() {
        return this._maxNumberOfRules;
    }

    /**
     * (no documentation provided)
     */
    public void setMaxNumberOfRules(int _maxNumberOfRules) {
        this._maxNumberOfRules = _maxNumberOfRules;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getCreatedBy() {
        return this._createdBy;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedBy(long _createdBy) {
        this._createdBy = _createdBy;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "provisioningStatus",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public com.eurotech.cloud.apis.v2.model.AccountProvisioningStatus getProvisioningStatus() {
        return this._provisioningStatus;
    }

    /**
     * (no documentation provided)
     */
    public void setProvisioningStatus(com.eurotech.cloud.apis.v2.model.AccountProvisioningStatus _provisioningStatus) {
        this._provisioningStatus = _provisioningStatus;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getModifiedBy() {
        return this._modifiedBy;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedBy(long _modifiedBy) {
        this._modifiedBy = _modifiedBy;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "atDeviceLimit",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public boolean getAtDeviceLimit() {
        return this._atDeviceLimit;
    }

    /**
     * (no documentation provided)
     */
    public void setAtDeviceLimit(boolean _atDeviceLimit) {
        this._atDeviceLimit = _atDeviceLimit;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getCreatedOn() {
        return this._createdOn;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedOn(java.util.Date _createdOn) {
        this._createdOn = _createdOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getModifiedOn() {
        return this._modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedOn(java.util.Date _modifiedOn) {
        this._modifiedOn = _modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "txByteLimit",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getTxByteLimit() {
        return this._txByteLimit;
    }

    /**
     * (no documentation provided)
     */
    public void setTxByteLimit(long _txByteLimit) {
        this._txByteLimit = _txByteLimit;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "dataStorageEnabled",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public boolean getDataStorageEnabled() {
        return this._dataStorageEnabled;
    }

    /**
     * (no documentation provided)
     */
    public void setDataStorageEnabled(boolean _dataStorageEnabled) {
        this._dataStorageEnabled = _dataStorageEnabled;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "dataTimeToLive",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public int getDataTimeToLive() {
        return this._dataTimeToLive;
    }

    /**
     * (no documentation provided)
     */
    public void setDataTimeToLive(int _dataTimeToLive) {
        this._dataTimeToLive = _dataTimeToLive;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "rxByteLimit",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getRxByteLimit() {
        return this._rxByteLimit;
    }

    /**
     * (no documentation provided)
     */
    public void setRxByteLimit(long _rxByteLimit) {
        this._rxByteLimit = _rxByteLimit;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "status",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public com.eurotech.cloud.apis.v2.model.AccountStatus getStatus() {
        return this._status;
    }

    /**
     * (no documentation provided)
     */
    public void setStatus(com.eurotech.cloud.apis.v2.model.AccountStatus _status) {
        this._status = _status;
    }

}
