// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "accountStatus",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlEnum (
    java.lang.String.class
)
public enum AccountStatus {

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "BEING_PROVISIONED" )
    BEING_PROVISIONED("BEING_PROVISIONED"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "ENABLED" )
    ENABLED("ENABLED"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "DISABLED" )
    DISABLED("DISABLED");

    private final String value;

    private AccountStatus(String value) {
        this.value = value;
    }

    public String toString() {
        return value;
    }

}
