// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "deviceCountResult",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "deviceCountResult",
    namespace = ""
)
public class DeviceCountResult implements java.io.Serializable {

    private long _count;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "count",
        namespace = ""
    )
    public long getCount() {
        return this._count;
    }

    /**
     * (no documentation provided)
     */
    public void setCount(long _count) {
        this._count = _count;
    }

}
