// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "deviceStatus",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlEnum (
    java.lang.String.class
)
public enum DeviceStatus {

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "CONNECTED" )
    CONNECTED("CONNECTED"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "DISCONNECTED" )
    DISCONNECTED("DISCONNECTED"),

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlEnumValue ( "MISSING" )
    MISSING("MISSING");

    private final String value;

    private DeviceStatus(String value) {
        this.value = value;
    }

    public String toString() {
        return value;
    }

}
