// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "device",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "device",
    namespace = "http://eurotech.com/edc/2.0"
)
public class Device implements java.io.Serializable {

    private java.lang.String _os;
    private java.lang.String _firmwareVersion;
    private long _uptime;
    private java.lang.String _modelName;
    private java.lang.String _jvmProfile;
    private java.lang.String _accountName;
    private java.lang.String _displayName;
    private java.util.Date _lastEventOn;
    private java.lang.String _partNumber;
    private java.lang.Double _gpsLatitude;
    private java.lang.String _jvmVersion;
    private java.lang.String _jvmName;
    private java.lang.String _modelId;
    private java.lang.String _biosVersion;
    private java.lang.String _osVersion;
    private java.lang.Double _gpsLongitude;
    private java.lang.String _connectionIp;
    private com.eurotech.cloud.apis.v2.model.DeviceStatus _status;
    private java.lang.String _serialNumber;
    private java.lang.String _connectionInterface;
    private java.lang.Double _gpsAltitude;
    private java.lang.String _clientId;
    private java.lang.String _lastEventType;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "os",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getOs() {
        return this._os;
    }

    /**
     * (no documentation provided)
     */
    public void setOs(java.lang.String _os) {
        this._os = _os;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "firmwareVersion",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getFirmwareVersion() {
        return this._firmwareVersion;
    }

    /**
     * (no documentation provided)
     */
    public void setFirmwareVersion(java.lang.String _firmwareVersion) {
        this._firmwareVersion = _firmwareVersion;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "uptime",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getUptime() {
        return this._uptime;
    }

    /**
     * (no documentation provided)
     */
    public void setUptime(long _uptime) {
        this._uptime = _uptime;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modelName",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getModelName() {
        return this._modelName;
    }

    /**
     * (no documentation provided)
     */
    public void setModelName(java.lang.String _modelName) {
        this._modelName = _modelName;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "jvmProfile",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getJvmProfile() {
        return this._jvmProfile;
    }

    /**
     * (no documentation provided)
     */
    public void setJvmProfile(java.lang.String _jvmProfile) {
        this._jvmProfile = _jvmProfile;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountName",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getAccountName() {
        return this._accountName;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountName(java.lang.String _accountName) {
        this._accountName = _accountName;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "displayName",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getDisplayName() {
        return this._displayName;
    }

    /**
     * (no documentation provided)
     */
    public void setDisplayName(java.lang.String _displayName) {
        this._displayName = _displayName;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "lastEventOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getLastEventOn() {
        return this._lastEventOn;
    }

    /**
     * (no documentation provided)
     */
    public void setLastEventOn(java.util.Date _lastEventOn) {
        this._lastEventOn = _lastEventOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "partNumber",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getPartNumber() {
        return this._partNumber;
    }

    /**
     * (no documentation provided)
     */
    public void setPartNumber(java.lang.String _partNumber) {
        this._partNumber = _partNumber;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "gpsLatitude",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.Double getGpsLatitude() {
        return this._gpsLatitude;
    }

    /**
     * (no documentation provided)
     */
    public void setGpsLatitude(java.lang.Double _gpsLatitude) {
        this._gpsLatitude = _gpsLatitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "jvmVersion",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getJvmVersion() {
        return this._jvmVersion;
    }

    /**
     * (no documentation provided)
     */
    public void setJvmVersion(java.lang.String _jvmVersion) {
        this._jvmVersion = _jvmVersion;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "jvmName",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getJvmName() {
        return this._jvmName;
    }

    /**
     * (no documentation provided)
     */
    public void setJvmName(java.lang.String _jvmName) {
        this._jvmName = _jvmName;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modelId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getModelId() {
        return this._modelId;
    }

    /**
     * (no documentation provided)
     */
    public void setModelId(java.lang.String _modelId) {
        this._modelId = _modelId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "biosVersion",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getBiosVersion() {
        return this._biosVersion;
    }

    /**
     * (no documentation provided)
     */
    public void setBiosVersion(java.lang.String _biosVersion) {
        this._biosVersion = _biosVersion;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "osVersion",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getOsVersion() {
        return this._osVersion;
    }

    /**
     * (no documentation provided)
     */
    public void setOsVersion(java.lang.String _osVersion) {
        this._osVersion = _osVersion;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "gpsLongitude",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.Double getGpsLongitude() {
        return this._gpsLongitude;
    }

    /**
     * (no documentation provided)
     */
    public void setGpsLongitude(java.lang.Double _gpsLongitude) {
        this._gpsLongitude = _gpsLongitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "connectionIp",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getConnectionIp() {
        return this._connectionIp;
    }

    /**
     * (no documentation provided)
     */
    public void setConnectionIp(java.lang.String _connectionIp) {
        this._connectionIp = _connectionIp;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "status",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public com.eurotech.cloud.apis.v2.model.DeviceStatus getStatus() {
        return this._status;
    }

    /**
     * (no documentation provided)
     */
    public void setStatus(com.eurotech.cloud.apis.v2.model.DeviceStatus _status) {
        this._status = _status;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "serialNumber",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getSerialNumber() {
        return this._serialNumber;
    }

    /**
     * (no documentation provided)
     */
    public void setSerialNumber(java.lang.String _serialNumber) {
        this._serialNumber = _serialNumber;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "connectionInterface",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getConnectionInterface() {
        return this._connectionInterface;
    }

    /**
     * (no documentation provided)
     */
    public void setConnectionInterface(java.lang.String _connectionInterface) {
        this._connectionInterface = _connectionInterface;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "gpsAltitude",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.Double getGpsAltitude() {
        return this._gpsAltitude;
    }

    /**
     * (no documentation provided)
     */
    public void setGpsAltitude(java.lang.Double _gpsAltitude) {
        this._gpsAltitude = _gpsAltitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "clientId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getClientId() {
        return this._clientId;
    }

    /**
     * (no documentation provided)
     */
    public void setClientId(java.lang.String _clientId) {
        this._clientId = _clientId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "lastEventType",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getLastEventType() {
        return this._lastEventType;
    }

    /**
     * (no documentation provided)
     */
    public void setLastEventType(java.lang.String _lastEventType) {
        this._lastEventType = _lastEventType;
    }

}
