// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "edcAssetInfo",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "assetInfo",
    namespace = ""
)
public class EdcAssetInfo implements java.io.Serializable {

    private java.lang.String _asset;
    private java.util.Date _lastMessageTimestamp;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "asset",
        namespace = ""
    )
    public java.lang.String getAsset() {
        return this._asset;
    }

    /**
     * (no documentation provided)
     */
    public void setAsset(java.lang.String _asset) {
        this._asset = _asset;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "lastMessageOn",
        namespace = ""
    )
    public java.util.Date getLastMessageTimestamp() {
        return this._lastMessageTimestamp;
    }

    /**
     * (no documentation provided)
     */
    public void setLastMessageTimestamp(java.util.Date _lastMessageTimestamp) {
        this._lastMessageTimestamp = _lastMessageTimestamp;
    }

}
