// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "edcPayload",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "payload",
    namespace = ""
)
public class EdcPayload implements java.io.Serializable {

    private java.util.Date _timestamp;
    private byte[] _body;
    private com.eurotech.cloud.apis.v2.model.EdcPosition _position;
    private com.eurotech.cloud.apis.v2.model.EdcMetricsMapType _metrics;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "sentOn",
        namespace = ""
    )
    public java.util.Date getTimestamp() {
        return this._timestamp;
    }

    /**
     * (no documentation provided)
     */
    public void setTimestamp(java.util.Date _timestamp) {
        this._timestamp = _timestamp;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "body",
        namespace = ""
    )
    @javax.xml.bind.annotation.XmlInlineBinaryData
    public byte[] getBody() {
        return this._body;
    }

    /**
     * (no documentation provided)
     */
    public void setBody(byte[] _body) {
        this._body = _body;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "position",
        namespace = ""
    )
    public com.eurotech.cloud.apis.v2.model.EdcPosition getPosition() {
        return this._position;
    }

    /**
     * (no documentation provided)
     */
    public void setPosition(com.eurotech.cloud.apis.v2.model.EdcPosition _position) {
        this._position = _position;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "metrics",
        namespace = ""
    )
    public com.eurotech.cloud.apis.v2.model.EdcMetricsMapType getMetrics() {
        return this._metrics;
    }

    /**
     * (no documentation provided)
     */
    public void setMetrics(com.eurotech.cloud.apis.v2.model.EdcMetricsMapType _metrics) {
        this._metrics = _metrics;
    }

}
