// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "edcPosition",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "position",
    namespace = ""
)
public class EdcPosition implements java.io.Serializable {

    private java.lang.Double _latitude;
    private java.lang.Double _heading;
    private java.lang.Double _altitude;
    private java.util.Date _timestamp;
    private java.lang.Double _longitude;
    private java.lang.Integer _satellites;
    private java.lang.Double _precision;
    private java.lang.Double _speed;
    private java.lang.Integer _status;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "latitude",
        namespace = ""
    )
    public java.lang.Double getLatitude() {
        return this._latitude;
    }

    /**
     * (no documentation provided)
     */
    public void setLatitude(java.lang.Double _latitude) {
        this._latitude = _latitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "heading",
        namespace = ""
    )
    public java.lang.Double getHeading() {
        return this._heading;
    }

    /**
     * (no documentation provided)
     */
    public void setHeading(java.lang.Double _heading) {
        this._heading = _heading;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "altitude",
        namespace = ""
    )
    public java.lang.Double getAltitude() {
        return this._altitude;
    }

    /**
     * (no documentation provided)
     */
    public void setAltitude(java.lang.Double _altitude) {
        this._altitude = _altitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "timestamp",
        namespace = ""
    )
    public java.util.Date getTimestamp() {
        return this._timestamp;
    }

    /**
     * (no documentation provided)
     */
    public void setTimestamp(java.util.Date _timestamp) {
        this._timestamp = _timestamp;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "longitude",
        namespace = ""
    )
    public java.lang.Double getLongitude() {
        return this._longitude;
    }

    /**
     * (no documentation provided)
     */
    public void setLongitude(java.lang.Double _longitude) {
        this._longitude = _longitude;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "satellites",
        namespace = ""
    )
    public java.lang.Integer getSatellites() {
        return this._satellites;
    }

    /**
     * (no documentation provided)
     */
    public void setSatellites(java.lang.Integer _satellites) {
        this._satellites = _satellites;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "precision",
        namespace = ""
    )
    public java.lang.Double getPrecision() {
        return this._precision;
    }

    /**
     * (no documentation provided)
     */
    public void setPrecision(java.lang.Double _precision) {
        this._precision = _precision;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "speed",
        namespace = ""
    )
    public java.lang.Double getSpeed() {
        return this._speed;
    }

    /**
     * (no documentation provided)
     */
    public void setSpeed(java.lang.Double _speed) {
        this._speed = _speed;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "status",
        namespace = ""
    )
    public java.lang.Integer getStatus() {
        return this._status;
    }

    /**
     * (no documentation provided)
     */
    public void setStatus(java.lang.Integer _status) {
        this._status = _status;
    }

}
