// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "errorBean",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "error",
    namespace = ""
)
public class ErrorBean implements java.io.Serializable {

    private int _code;
    private java.lang.String _reason;
    private java.lang.String _message;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "code",
        namespace = ""
    )
    public int getCode() {
        return this._code;
    }

    /**
     * (no documentation provided)
     */
    public void setCode(int _code) {
        this._code = _code;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "reason",
        namespace = ""
    )
    public java.lang.String getReason() {
        return this._reason;
    }

    /**
     * (no documentation provided)
     */
    public void setReason(java.lang.String _reason) {
        this._reason = _reason;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "message",
        namespace = ""
    )
    public java.lang.String getMessage() {
        return this._message;
    }

    /**
     * (no documentation provided)
     */
    public void setMessage(java.lang.String _message) {
        this._message = _message;
    }

}
