// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "messagesResult",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "messagesResult",
    namespace = ""
)
public class MessagesResult implements java.io.Serializable {

    private java.util.List<com.eurotech.cloud.apis.v2.model.EdcMessage> _messages;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "message",
        namespace = ""
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.EdcMessage> getMessages() {
        return this._messages;
    }

    /**
     * (no documentation provided)
     */
    public void setMessages(java.util.List<com.eurotech.cloud.apis.v2.model.EdcMessage> _messages) {
        this._messages = _messages;
    }

}
