// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "metricsResult",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "metricsResult",
    namespace = ""
)
public class MetricsResult implements java.io.Serializable {

    private java.util.List<com.eurotech.cloud.apis.v2.model.EdcMetric> _metrics;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "metricInfo",
        namespace = ""
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.EdcMetric> getMetrics() {
        return this._metrics;
    }

    /**
     * (no documentation provided)
     */
    public void setMetrics(java.util.List<com.eurotech.cloud.apis.v2.model.EdcMetric> _metrics) {
        this._metrics = _metrics;
    }

}
