// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "organization",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "organization",
    namespace = "http://eurotech.com/edc/2.0"
)
public class Organization implements java.io.Serializable {

    private java.lang.String _stateProvinceCounty;
    private java.lang.String _addressLine2;
    private java.lang.String _addressLine1;
    private java.lang.String _country;
    private java.lang.String _addressLine3;
    private java.lang.String _name;
    private java.lang.String _city;
    private java.lang.String _zipPostCode;
    private java.lang.String _phoneNumber;
    private java.lang.String _email;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "stateProvinceCounty",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getStateProvinceCounty() {
        return this._stateProvinceCounty;
    }

    /**
     * (no documentation provided)
     */
    public void setStateProvinceCounty(java.lang.String _stateProvinceCounty) {
        this._stateProvinceCounty = _stateProvinceCounty;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "addressLine2",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getAddressLine2() {
        return this._addressLine2;
    }

    /**
     * (no documentation provided)
     */
    public void setAddressLine2(java.lang.String _addressLine2) {
        this._addressLine2 = _addressLine2;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "addressLine1",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getAddressLine1() {
        return this._addressLine1;
    }

    /**
     * (no documentation provided)
     */
    public void setAddressLine1(java.lang.String _addressLine1) {
        this._addressLine1 = _addressLine1;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "country",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getCountry() {
        return this._country;
    }

    /**
     * (no documentation provided)
     */
    public void setCountry(java.lang.String _country) {
        this._country = _country;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "addressLine3",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getAddressLine3() {
        return this._addressLine3;
    }

    /**
     * (no documentation provided)
     */
    public void setAddressLine3(java.lang.String _addressLine3) {
        this._addressLine3 = _addressLine3;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "city",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getCity() {
        return this._city;
    }

    /**
     * (no documentation provided)
     */
    public void setCity(java.lang.String _city) {
        this._city = _city;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "zipPostCode",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getZipPostCode() {
        return this._zipPostCode;
    }

    /**
     * (no documentation provided)
     */
    public void setZipPostCode(java.lang.String _zipPostCode) {
        this._zipPostCode = _zipPostCode;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "phoneNumber",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getPhoneNumber() {
        return this._phoneNumber;
    }

    /**
     * (no documentation provided)
     */
    public void setPhoneNumber(java.lang.String _phoneNumber) {
        this._phoneNumber = _phoneNumber;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "email",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getEmail() {
        return this._email;
    }

    /**
     * (no documentation provided)
     */
    public void setEmail(java.lang.String _email) {
        this._email = _email;
    }

}
