// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "roleCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "roleCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
public class RoleCreator implements java.io.Serializable {

    private java.lang.String _name;
    private long _accountId;
    private java.util.Set<java.lang.String> _permissions;
    private java.lang.String _tags;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "permission",
        namespace = "http://eurotech.com/edc/2.0"
    )
    @javax.xml.bind.annotation.XmlElementWrapper (
        name = "permissions",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Set<java.lang.String> getPermissions() {
        return this._permissions;
    }

    /**
     * (no documentation provided)
     */
    public void setPermissions(java.util.Set<java.lang.String> _permissions) {
        this._permissions = _permissions;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "tags",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getTags() {
        return this._tags;
    }

    /**
     * (no documentation provided)
     */
    public void setTags(java.lang.String _tags) {
        this._tags = _tags;
    }

}
