// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "role",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "role",
    namespace = "http://eurotech.com/edc/2.0"
)
public class Role implements java.io.Serializable {

    private long _accountId;
    private java.lang.String _tags;
    private java.util.Set<java.lang.String> _permissions;
    private long _createdBy;
    private long _id;
    private int _optlock;
    private java.lang.String _name;
    private java.util.Date _createdOn;
    private java.util.Date _modifiedOn;
    private long _modifiedBy;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "tags",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getTags() {
        return this._tags;
    }

    /**
     * (no documentation provided)
     */
    public void setTags(java.lang.String _tags) {
        this._tags = _tags;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "permission",
        namespace = "http://eurotech.com/edc/2.0"
    )
    @javax.xml.bind.annotation.XmlElementWrapper (
        name = "permissions",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Set<java.lang.String> getPermissions() {
        return this._permissions;
    }

    /**
     * (no documentation provided)
     */
    public void setPermissions(java.util.Set<java.lang.String> _permissions) {
        this._permissions = _permissions;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getCreatedBy() {
        return this._createdBy;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedBy(long _createdBy) {
        this._createdBy = _createdBy;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "id",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getId() {
        return this._id;
    }

    /**
     * (no documentation provided)
     */
    public void setId(long _id) {
        this._id = _id;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "optlock",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public int getOptlock() {
        return this._optlock;
    }

    /**
     * (no documentation provided)
     */
    public void setOptlock(int _optlock) {
        this._optlock = _optlock;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getCreatedOn() {
        return this._createdOn;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedOn(java.util.Date _createdOn) {
        this._createdOn = _createdOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getModifiedOn() {
        return this._modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedOn(java.util.Date _modifiedOn) {
        this._modifiedOn = _modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getModifiedBy() {
        return this._modifiedBy;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedBy(long _modifiedBy) {
        this._modifiedBy = _modifiedBy;
    }

}
