// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "ruleCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "ruleCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
public class RuleCreator implements java.io.Serializable {

    private java.lang.String _name;
    private long _accountId;
    private boolean _enabled;
    private java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> _ruleActionConfigurations;
    private java.lang.String _query;
    private java.lang.String _description;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "enabled",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public boolean getEnabled() {
        return this._enabled;
    }

    /**
     * (no documentation provided)
     */
    public void setEnabled(boolean _enabled) {
        this._enabled = _enabled;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "ruleActionConfiguration",
        namespace = "http://eurotech.com/edc/2.0"
    )
    @javax.xml.bind.annotation.XmlElementWrapper (
        name = "ruleActionConfigurations",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> getRuleActionConfigurations() {
        return this._ruleActionConfigurations;
    }

    /**
     * (no documentation provided)
     */
    public void setRuleActionConfigurations(java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> _ruleActionConfigurations) {
        this._ruleActionConfigurations = _ruleActionConfigurations;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "query",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getQuery() {
        return this._query;
    }

    /**
     * (no documentation provided)
     */
    public void setQuery(java.lang.String _query) {
        this._query = _query;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "description",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getDescription() {
        return this._description;
    }

    /**
     * (no documentation provided)
     */
    public void setDescription(java.lang.String _description) {
        this._description = _description;
    }

}
