// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "rule",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "rule",
    namespace = "http://eurotech.com/edc/2.0"
)
public class Rule implements java.io.Serializable {

    private java.util.Date _modifiedOn;
    private java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> _ruleActionConfigurations;
    private long _modifiedBy;
    private java.util.Date _synchronizedOn;
    private java.util.Date _createdOn;
    private java.lang.String _name;
    private java.lang.String _query;
    private long _createdBy;
    private boolean _enabled;
    private java.lang.String _description;
    private long _accountId;
    private long _id;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getModifiedOn() {
        return this._modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedOn(java.util.Date _modifiedOn) {
        this._modifiedOn = _modifiedOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "ruleActionConfiguration",
        namespace = "http://eurotech.com/edc/2.0"
    )
    @javax.xml.bind.annotation.XmlElementWrapper (
        name = "ruleActionConfigurations",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> getRuleActionConfigurations() {
        return this._ruleActionConfigurations;
    }

    /**
     * (no documentation provided)
     */
    public void setRuleActionConfigurations(java.util.List<com.eurotech.cloud.apis.v2.model.RuleActionConfiguration> _ruleActionConfigurations) {
        this._ruleActionConfigurations = _ruleActionConfigurations;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "modifiedBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getModifiedBy() {
        return this._modifiedBy;
    }

    /**
     * (no documentation provided)
     */
    public void setModifiedBy(long _modifiedBy) {
        this._modifiedBy = _modifiedBy;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "synchronizedOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getSynchronizedOn() {
        return this._synchronizedOn;
    }

    /**
     * (no documentation provided)
     */
    public void setSynchronizedOn(java.util.Date _synchronizedOn) {
        this._synchronizedOn = _synchronizedOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdOn",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.util.Date getCreatedOn() {
        return this._createdOn;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedOn(java.util.Date _createdOn) {
        this._createdOn = _createdOn;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "query",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getQuery() {
        return this._query;
    }

    /**
     * (no documentation provided)
     */
    public void setQuery(java.lang.String _query) {
        this._query = _query;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "createdBy",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getCreatedBy() {
        return this._createdBy;
    }

    /**
     * (no documentation provided)
     */
    public void setCreatedBy(long _createdBy) {
        this._createdBy = _createdBy;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "enabled",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public boolean getEnabled() {
        return this._enabled;
    }

    /**
     * (no documentation provided)
     */
    public void setEnabled(boolean _enabled) {
        this._enabled = _enabled;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "description",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getDescription() {
        return this._description;
    }

    /**
     * (no documentation provided)
     */
    public void setDescription(java.lang.String _description) {
        this._description = _description;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "id",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getId() {
        return this._id;
    }

    /**
     * (no documentation provided)
     */
    public void setId(long _id) {
        this._id = _id;
    }

}
