// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "ruleActionConfiguration",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "ruleActionConfiguration",
    namespace = "http://eurotech.com/edc/2.0"
)
public class RuleActionConfiguration implements java.io.Serializable {

    private com.eurotech.cloud.apis.v2.model.xml.ParametersMapType _parameterValues;
    private java.lang.String _ruleActionInfoName;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "parameters",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public com.eurotech.cloud.apis.v2.model.xml.ParametersMapType getParameterValues() {
        return this._parameterValues;
    }

    /**
     * (no documentation provided)
     */
    public void setParameterValues(com.eurotech.cloud.apis.v2.model.xml.ParametersMapType _parameterValues) {
        this._parameterValues = _parameterValues;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getRuleActionInfoName() {
        return this._ruleActionInfoName;
    }

    /**
     * (no documentation provided)
     */
    public void setRuleActionInfoName(java.lang.String _ruleActionInfoName) {
        this._ruleActionInfoName = _ruleActionInfoName;
    }

}
