// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "topicsResult",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "topicsResult",
    namespace = ""
)
public class TopicsResult implements java.io.Serializable {

    private java.util.List<com.eurotech.cloud.apis.v2.model.EdcTopicInfo> _topics;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "topicInfo",
        namespace = ""
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.EdcTopicInfo> getTopics() {
        return this._topics;
    }

    /**
     * (no documentation provided)
     */
    public void setTopics(java.util.List<com.eurotech.cloud.apis.v2.model.EdcTopicInfo> _topics) {
        this._topics = _topics;
    }

}
