// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "userCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "userCreator",
    namespace = "http://eurotech.com/edc/2.0"
)
public class UserCreator implements java.io.Serializable {

    private java.lang.String _email;
    private java.lang.String _username;
    private java.lang.String _password;
    private long _accountId;
    private java.lang.String _phoneNumber;
    private java.lang.String _displayName;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "email",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getEmail() {
        return this._email;
    }

    /**
     * (no documentation provided)
     */
    public void setEmail(java.lang.String _email) {
        this._email = _email;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "username",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getUsername() {
        return this._username;
    }

    /**
     * (no documentation provided)
     */
    public void setUsername(java.lang.String _username) {
        this._username = _username;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "password",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getPassword() {
        return this._password;
    }

    /**
     * (no documentation provided)
     */
    public void setPassword(java.lang.String _password) {
        this._password = _password;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "accountId",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public long getAccountId() {
        return this._accountId;
    }

    /**
     * (no documentation provided)
     */
    public void setAccountId(long _accountId) {
        this._accountId = _accountId;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "phoneNumber",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getPhoneNumber() {
        return this._phoneNumber;
    }

    /**
     * (no documentation provided)
     */
    public void setPhoneNumber(java.lang.String _phoneNumber) {
        this._phoneNumber = _phoneNumber;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "displayName",
        namespace = "http://eurotech.com/edc/2.0"
    )
    public java.lang.String getDisplayName() {
        return this._displayName;
    }

    /**
     * (no documentation provided)
     */
    public void setDisplayName(java.lang.String _displayName) {
        this._displayName = _displayName;
    }

}
