// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
  name = "versionResult",
  namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
  name = "versionResult",
  namespace = ""
)
public class VersionResult implements java.io.Serializable {

  private java.lang.String _m_version;
  private java.lang.String _m_buildVersion;
  private java.lang.String _m_buildNumber;

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "version",
    namespace = ""
  )
  public java.lang.String getM_version() {
    return this._m_version;
  }

  /**
   * (no documentation provided)
   */
  public void setM_version(java.lang.String _m_version) {
    this._m_version = _m_version;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "buildVersion",
    namespace = ""
  )
  public java.lang.String getM_buildVersion() {
    return this._m_buildVersion;
  }

  /**
   * (no documentation provided)
   */
  public void setM_buildVersion(java.lang.String _m_buildVersion) {
    this._m_buildVersion = _m_buildVersion;
  }

  /**
   * (no documentation provided)
   */
  @javax.xml.bind.annotation.XmlElement (
    name = "buildNumber",
    namespace = ""
  )
  public java.lang.String getM_buildNumber() {
    return this._m_buildNumber;
  }

  /**
   * (no documentation provided)
   */
  public void setM_buildNumber(java.lang.String _m_buildNumber) {
    this._m_buildNumber = _m_buildNumber;
  }

}
