// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model.xml;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "parameter",
    namespace = ""
)
@javax.xml.bind.annotation.XmlRootElement (
    name = "parameter",
    namespace = ""
)
public class Parameter implements java.io.Serializable {

    private java.lang.String _name;
    private java.lang.String _value;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "name",
        namespace = ""
    )
    public java.lang.String getName() {
        return this._name;
    }

    /**
     * (no documentation provided)
     */
    public void setName(java.lang.String _name) {
        this._name = _name;
    }

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "value",
        namespace = ""
    )
    public java.lang.String getValue() {
        return this._value;
    }

    /**
     * (no documentation provided)
     */
    public void setValue(java.lang.String _value) {
        this._value = _value;
    }

}
