// Generated by Enunciate
package com.eurotech.cloud.apis.v2.model.xml;

/**
 * (no documentation provided)
 */
@javax.xml.bind.annotation.XmlType (
    name = "parametersMapType",
    namespace = ""
)
public class ParametersMapType implements java.io.Serializable {

    private java.util.List<com.eurotech.cloud.apis.v2.model.xml.Parameter> _parameters;

    /**
     * (no documentation provided)
     */
    @javax.xml.bind.annotation.XmlElement (
        name = "parameter",
        namespace = ""
    )
    public java.util.List<com.eurotech.cloud.apis.v2.model.xml.Parameter> getParameters() {
        return this._parameters;
    }

    /**
     * (no documentation provided)
     */
    public void setParameters(java.util.List<com.eurotech.cloud.apis.v2.model.xml.Parameter> _parameters) {
        this._parameters = _parameters;
    }

}
